import { jsPDF } from "jspdf";

interface PDFSection {
  title?: string;
  content: string;
}

interface PDFOptions {
  title: string;
  subtitle?: string;
  date?: string;
  sections: PDFSection[];
  footer?: string;
}

export function exportToPDF(options: PDFOptions) {
  const { title, subtitle, date, sections, footer } = options;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const addPageIfNeeded = (requiredSpace: number) => {
    if (y + requiredSpace > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = margin;
    }
  };

  // Header bar
  doc.setFillColor(20, 20, 25);
  doc.rect(0, 0, pageWidth, 35, "F");
  doc.setFillColor(220, 38, 38);
  doc.rect(0, 35, pageWidth, 1, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, margin, 15);

  if (subtitle) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(180, 180, 180);
    doc.text(subtitle, margin, 22);
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(date || new Date().toLocaleDateString(), margin, 30);
  doc.text("CRISIS-X PLATFORM", pageWidth - margin, 30, { align: "right" });

  y = 45;
  doc.setTextColor(30, 30, 30);

  for (const section of sections) {
    if (section.title) {
      addPageIfNeeded(15);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(220, 38, 38);
      doc.text(section.title.toUpperCase(), margin, y);
      y += 2;
      doc.setDrawColor(220, 38, 38);
      doc.setLineWidth(0.3);
      doc.line(margin, y, margin + 40, y);
      y += 6;
    }

    // Parse markdown-like content into plain text lines
    const lines = section.content.split("\n");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);

    for (const rawLine of lines) {
      let line = rawLine;
      let isBold = false;
      let isBullet = false;
      let isH2 = false;
      let isH3 = false;

      // Handle markdown headers
      if (line.startsWith("### ")) {
        line = line.slice(4);
        isH3 = true;
      } else if (line.startsWith("## ")) {
        line = line.slice(3);
        isH2 = true;
      } else if (line.startsWith("# ")) {
        line = line.slice(2);
        isH2 = true;
      }

      // Handle bullets
      if (line.startsWith("- ") || line.startsWith("* ")) {
        line = line.slice(2);
        isBullet = true;
      } else if (/^\d+\.\s/.test(line)) {
        isBullet = true;
      }

      // Handle bold markers
      if (line.startsWith("**") && line.endsWith("**")) {
        line = line.slice(2, -2);
        isBold = true;
      }
      // Strip remaining markdown
      line = line.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1").replace(/`(.*?)`/g, "$1");

      if (line.trim() === "" || line.trim() === "---") {
        y += 3;
        continue;
      }

      if (isH2) {
        addPageIfNeeded(12);
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 30, 30);
        const wrapped = doc.splitTextToSize(line, maxWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 5 + 3;
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(50, 50, 50);
        continue;
      }

      if (isH3) {
        addPageIfNeeded(10);
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(60, 60, 60);
        const wrapped = doc.splitTextToSize(line, maxWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 4.5 + 2;
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(50, 50, 50);
        continue;
      }

      const indent = isBullet ? 4 : 0;
      const textWidth = maxWidth - indent;

      if (isBold) {
        doc.setFont("helvetica", "bold");
      }

      const wrapped = doc.splitTextToSize(line, textWidth);
      addPageIfNeeded(wrapped.length * 4.5);

      if (isBullet) {
        doc.setFillColor(220, 38, 38);
        doc.circle(margin + 1.2, y - 1, 0.6, "F");
      }

      doc.text(wrapped, margin + indent, y);
      y += wrapped.length * 4.5;

      if (isBold) {
        doc.setFont("helvetica", "normal");
      }
    }

    y += 6;
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      footer || "Generated by Crisis-X Platform",
      margin,
      doc.internal.pageSize.getHeight() - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" }
    );
  }

  const filename = `${title.replace(/[^a-zA-Z0-9]/g, "_").toLowerCase()}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
